// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for Lifecycle.
const (
	Beta       Lifecycle = "beta"
	Deprecated Lifecycle = "deprecated"
	Production Lifecycle = "production"
)

// Valid indicates whether the value is a known member of the Lifecycle enum.
func (e Lifecycle) Valid() bool {
	switch e {
	case Beta:
		return true
	case Deprecated:
		return true
	case Production:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Message Human-readable message
	Message string `json:"message"`
}

// Lifecycle Lifecycle stage of a service
type Lifecycle string

// Service defines model for Service.
type Service struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// Lifecycle Lifecycle stage of a service
	Lifecycle  Lifecycle `json:"lifecycle"`
	Name       string    `json:"name"`
	RepoUrl    *string   `json:"repoUrl,omitempty"`
	RunbookUrl *string   `json:"runbookUrl,omitempty"`
	Slug       string    `json:"slug"`
	Tags       []string  `json:"tags"`

	// Team Reference to the owning team
	Team      TeamRef   `json:"team"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ServiceCreate defines model for ServiceCreate.
type ServiceCreate struct {
	Description *string `json:"description,omitempty"`

	// Lifecycle Lifecycle stage of a service
	Lifecycle  Lifecycle          `json:"lifecycle"`
	Name       string             `json:"name"`
	RepoUrl    *string            `json:"repoUrl,omitempty"`
	RunbookUrl *string            `json:"runbookUrl,omitempty"`
	Slug       string             `json:"slug"`
	Tags       *[]string          `json:"tags,omitempty"`
	TeamId     openapi_types.UUID `json:"teamId"`
}

// ServiceList defines model for ServiceList.
type ServiceList struct {
	Items []Service `json:"items"`
}

// ServiceUpdate defines model for ServiceUpdate.
type ServiceUpdate struct {
	Description *string `json:"description,omitempty"`

	// Lifecycle Lifecycle stage of a service
	Lifecycle  Lifecycle          `json:"lifecycle"`
	Name       string             `json:"name"`
	RepoUrl    *string            `json:"repoUrl,omitempty"`
	RunbookUrl *string            `json:"runbookUrl,omitempty"`
	Tags       *[]string          `json:"tags,omitempty"`
	TeamId     openapi_types.UUID `json:"teamId"`
}

// Team defines model for Team.
type Team struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
}

// TeamList defines model for TeamList.
type TeamList struct {
	Items []Team `json:"items"`
}

// TeamRef Reference to the owning team
type TeamRef struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// Team Filter by owning team slug
	Team *string `form:"team,omitempty" json:"team,omitempty"`

	// Lifecycle Filter by lifecycle stage
	Lifecycle *Lifecycle `form:"lifecycle,omitempty" json:"lifecycle,omitempty"`

	// Tag Filter by tag name
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Q Free-text search over name and description
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = ServiceCreate

// UpdateServiceJSONRequestBody defines body for UpdateService for application/json ContentType.
type UpdateServiceJSONRequestBody = ServiceUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List services
	// (GET /services)
	ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams)
	// Register a new service
	// (POST /services)
	CreateService(w http.ResponseWriter, r *http.Request)
	// Delete a service
	// (DELETE /services/{serviceId})
	DeleteService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID)
	// Get a service by id
	// (GET /services/{serviceId})
	GetService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID)
	// Update a service
	// (PUT /services/{serviceId})
	UpdateService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID)
	// List teams
	// (GET /teams)
	ListTeams(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List services
// (GET /services)
func (_ Unimplemented) ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new service
// (POST /services)
func (_ Unimplemented) CreateService(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a service
// (DELETE /services/{serviceId})
func (_ Unimplemented) DeleteService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a service by id
// (GET /services/{serviceId})
func (_ Unimplemented) GetService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a service
// (PUT /services/{serviceId})
func (_ Unimplemented) UpdateService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List teams
// (GET /teams)
func (_ Unimplemented) ListTeams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams

	// ------------- Optional query parameter "team" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "team", r.URL.Query(), &params.Team, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lifecycle" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lifecycle", r.URL.Query(), &params.Lifecycle, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lifecycle"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lifecycle", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateService operation middleware
func (siw *ServerInterfaceWrapper) CreateService(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceId" -------------
	var serviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceId" -------------
	var serviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateService operation middleware
func (siw *ServerInterfaceWrapper) UpdateService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceId" -------------
	var serviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTeams operation middleware
func (siw *ServerInterfaceWrapper) ListTeams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTeams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services", wrapper.ListServices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services", wrapper.CreateService)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/services/{serviceId}", wrapper.DeleteService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/{serviceId}", wrapper.GetService)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/services/{serviceId}", wrapper.UpdateService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/teams", wrapper.ListTeams)
	})

	return r
}

type ErrorResponseJSONResponse Error

type ListServicesRequestObject struct {
	Params ListServicesParams
}

type ListServicesResponseObject interface {
	VisitListServicesResponse(w http.ResponseWriter) error
}

type ListServices200JSONResponse ServiceList

func (response ListServices200JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListServices401JSONResponse struct{ ErrorResponseJSONResponse }

func (response ListServices401JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListServicesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListServicesdefaultJSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServiceRequestObject struct {
	Body *CreateServiceJSONRequestBody
}

type CreateServiceResponseObject interface {
	VisitCreateServiceResponse(w http.ResponseWriter) error
}

type CreateService201JSONResponse Service

func (response CreateService201JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateService400JSONResponse struct{ ErrorResponseJSONResponse }

func (response CreateService400JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateService409JSONResponse Error

func (response CreateService409JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateServicedefaultJSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServiceRequestObject struct {
	ServiceId openapi_types.UUID `json:"serviceId"`
}

type DeleteServiceResponseObject interface {
	VisitDeleteServiceResponse(w http.ResponseWriter) error
}

type DeleteService204Response struct {
}

func (response DeleteService204Response) VisitDeleteServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteService404JSONResponse struct{ ErrorResponseJSONResponse }

func (response DeleteService404JSONResponse) VisitDeleteServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteServicedefaultJSONResponse) VisitDeleteServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetServiceRequestObject struct {
	ServiceId openapi_types.UUID `json:"serviceId"`
}

type GetServiceResponseObject interface {
	VisitGetServiceResponse(w http.ResponseWriter) error
}

type GetService200JSONResponse Service

func (response GetService200JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetService404JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetService404JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetServicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetServicedefaultJSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServiceRequestObject struct {
	ServiceId openapi_types.UUID `json:"serviceId"`
	Body      *UpdateServiceJSONRequestBody
}

type UpdateServiceResponseObject interface {
	VisitUpdateServiceResponse(w http.ResponseWriter) error
}

type UpdateService200JSONResponse Service

func (response UpdateService200JSONResponse) VisitUpdateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateService400JSONResponse struct{ ErrorResponseJSONResponse }

func (response UpdateService400JSONResponse) VisitUpdateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateService404JSONResponse Error

func (response UpdateService404JSONResponse) VisitUpdateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateServicedefaultJSONResponse) VisitUpdateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListTeamsRequestObject struct {
}

type ListTeamsResponseObject interface {
	VisitListTeamsResponse(w http.ResponseWriter) error
}

type ListTeams200JSONResponse TeamList

func (response ListTeams200JSONResponse) VisitListTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTeams401JSONResponse struct{ ErrorResponseJSONResponse }

func (response ListTeams401JSONResponse) VisitListTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTeamsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListTeamsdefaultJSONResponse) VisitListTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List services
	// (GET /services)
	ListServices(ctx context.Context, request ListServicesRequestObject) (ListServicesResponseObject, error)
	// Register a new service
	// (POST /services)
	CreateService(ctx context.Context, request CreateServiceRequestObject) (CreateServiceResponseObject, error)
	// Delete a service
	// (DELETE /services/{serviceId})
	DeleteService(ctx context.Context, request DeleteServiceRequestObject) (DeleteServiceResponseObject, error)
	// Get a service by id
	// (GET /services/{serviceId})
	GetService(ctx context.Context, request GetServiceRequestObject) (GetServiceResponseObject, error)
	// Update a service
	// (PUT /services/{serviceId})
	UpdateService(ctx context.Context, request UpdateServiceRequestObject) (UpdateServiceResponseObject, error)
	// List teams
	// (GET /teams)
	ListTeams(ctx context.Context, request ListTeamsRequestObject) (ListTeamsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListServices operation middleware
func (sh *strictHandler) ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams) {
	var request ListServicesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListServices(ctx, request.(ListServicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListServicesResponseObject); ok {
		if err := validResponse.VisitListServicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateService operation middleware
func (sh *strictHandler) CreateService(w http.ResponseWriter, r *http.Request) {
	var request CreateServiceRequestObject

	var body CreateServiceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateService(ctx, request.(CreateServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateService")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateServiceResponseObject); ok {
		if err := validResponse.VisitCreateServiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteService operation middleware
func (sh *strictHandler) DeleteService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID) {
	var request DeleteServiceRequestObject

	request.ServiceId = serviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteService(ctx, request.(DeleteServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteService")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteServiceResponseObject); ok {
		if err := validResponse.VisitDeleteServiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetService operation middleware
func (sh *strictHandler) GetService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID) {
	var request GetServiceRequestObject

	request.ServiceId = serviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetService(ctx, request.(GetServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetService")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetServiceResponseObject); ok {
		if err := validResponse.VisitGetServiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateService operation middleware
func (sh *strictHandler) UpdateService(w http.ResponseWriter, r *http.Request, serviceId openapi_types.UUID) {
	var request UpdateServiceRequestObject

	request.ServiceId = serviceId

	var body UpdateServiceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateService(ctx, request.(UpdateServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateService")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateServiceResponseObject); ok {
		if err := validResponse.VisitUpdateServiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTeams operation middleware
func (sh *strictHandler) ListTeams(w http.ResponseWriter, r *http.Request) {
	var request ListTeamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTeams(ctx, request.(ListTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTeams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTeamsResponseObject); ok {
		if err := validResponse.VisitListTeamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FhLcts2GL4KBs2iD1qiE2+iXdq81IknGVuZLlx1BgJ/UUhIgAF+OlE9nOkheoTcJDfpSTo/+JYo2XFd",
	"q4vuQDz+5/e/eMWlSTOjQaPjkytuwWVGO/Afz6w19qzaoQ1pNIJGWoosS5QUqIwev3NG056TK0gFrR5Y",
	"WPIJ/2bcUh+Xp27sqfKiKAIegZNWZUSET3h9EFSEWhlokVmTgUVViiZN5CXqUzgVcqU0HFkQkVgkwIBe",
	"M3854LjOgE+4Q6t0zIuAp+CciAfovMxToVsq9b0tEkXALXzIlYWITy54xae+Pm/um8U7kEgsX6klyLVM",
	"Bpg2R8yhiIGZJRPMgb1UkqiCzlNiklkT5dK/CfgCUHCyY2ZBCoSow7TV87wism1FC/Toiffo0thUIJ/w",
	"SCAcoUoHbdaT+Wr7XEU9WnmuoiEySdcO+9DSGqwIuBYpDHK1kJm3NumztmqIs831wpj3N7ztkjwe5Igi",
	"9iZUCKkbvlFuCGvF2n+DSK/TdgYiPYMlXc+z6Ot8swFGb3dvsEqLrtEraSo1gg4QuoyHAFxh6Sf/YBtR",
	"G/BIxadXoGNc8cnDMAzvHAgd+scPw4CnSjffwQFgsilPJhDBUnT/diGOfg+PHs9/+PaoWX73/YMharfD",
	"1vQmkbcBkj4+Kipdp+yBwCvlcBsAjczNYp9T68y0pdImmD2xPcK89aD9H4+HQtBmaplGg96aVTnwH5eh",
	"G5aZnQVjR16/Poe2su7S7y7iwtvp9kFRl5GtHuMMlmBBS2BoGK6AmY9a6ZhV1WBD5MPYeFshogUytwrX",
	"52SgUrwFCAv2SU7BVX89r4X9+ZcZ3+wvT5W0xpklsmcarWDTp0xICc4xNO+B2ilvfuJcUmu1XSFmZcuq",
	"9NLUrbCQ3tGlAfhrdIa9BKW/fE6/fH6vtrqlOlcxKVAkJmZP3kwn3vQuqBs9F7AIMtARaKnAMaEjusZc",
	"BtKN2GylnF8z5bz/nNIxdYwmt9K3jGhzXLG//vjTH78wnjBYpjSCXQpZ0aTD2TqDcy8ek4kCjUxYYAuD",
	"KxaDBks4Z0trUqZw9Kv2US6hGgUqpU+nZOecspI3kpuMxyYDXQo0MjYeV4/GqfLYRIWUXPmUBNIiYU/h",
	"EhLCHXtjLIqE9OUBvwTrSrOFo+NRSE+JsMgUn/BHo3D0iPv6uvJgGNf2o48YvF+Iph9QKK9xCsvz+hK9",
	"tCIFBOv45GIzTJ6rBMGyxbobH6zKAIpufMjBrmvgTupuqh2AtjC/m0XS7/t3cOgm2JvNWZ0CtY89iphV",
	"4TeomYi/UjELcITwCZkDYeWKGYIfUfPA614e5vhhL7950J9RH4bhnU2m3cZmYD6lfQqxBmpFwE/C411U",
	"GzHH/Tna012KPMGvfkmJME9TYde1OK5FdFnzL3izNS8Cnhk3EAtl937ezJaUj8HhjyZa37Uxq0Gh6Kd9",
	"tDkUW548vmvmQ15sknBZyEsnhrdw4kn4+FCuP4NYOYpfwTR87PwkGMBAEbTJcXxVraZRUTYHCZRdcx8f",
	"T/1+Fx89P51sNxbli8qaJ4eySylF77fJYFQMFogXgDs1Du8DmTOq5+1AdEA7vgBsjUhFouz8BhNMv476",
	"hE5Vuc3nDeT4Zgbo5vnrpo55wLN8wGvl4HcvqayaMW+Uyu4FMKVAUR80t0tlB4NaqcN1IUtJzDfKe9u7",
	"mb/xL/qiGe/2dAelmP+B1gAra9TmLL/nRXec8jHbHaQu5hRp5cww1BmfmlwT5HIdgWVjkanx5bFvI6vk",
	"5aemch6oTjlRrIS4umYiAo1W+W6mnzzIoJtvX7etuet34o4X8+LvAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
