/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List services */
        get: operations["ListServices"];
        put?: never;
        /** Register a new service */
        post: operations["CreateService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: string;
            };
            cookie?: never;
        };
        /** Get a service by id */
        get: operations["GetService"];
        /** Update a service */
        put: operations["UpdateService"];
        post?: never;
        /**
         * Delete a service
         * @description Requires the ADMIN role on the owning team.
         */
        delete: operations["DeleteService"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams */
        get: operations["ListTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user and their per-team roles
         * @description Roles are read from the database on every call rather than carried in the token, so membership changes take effect without re-authenticating.
         */
        get: operations["GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Lifecycle stage of a service
         * @enum {string}
         */
        Lifecycle: "production" | "beta" | "deprecated";
        /**
         * @description Role held within a single team
         * @enum {string}
         */
        Role: "ADMIN" | "EDITOR" | "VIEWER";
        /** @description A team the user belongs to, and their role in it. Team name and slug are denormalized so the UI can render a team picker from this alone. */
        TeamRole: {
            /** Format: uuid */
            teamId: string;
            teamSlug: string;
            teamName: string;
            role: components["schemas"]["Role"];
        };
        /** @description The signed-in user. An empty teamRoles list still grants read access to the whole catalog — every authenticated user is an implicit viewer. */
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            teamRoles: components["schemas"]["TeamRole"][];
        };
        /** @description Reference to the owning team */
        TeamRef: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            createdAt: string;
        };
        TeamList: {
            items: components["schemas"]["Team"][];
        };
        Service: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
            lifecycle: components["schemas"]["Lifecycle"];
            /** Format: uri */
            repoUrl?: string;
            /** Format: uri */
            runbookUrl?: string;
            team: components["schemas"]["TeamRef"];
            tags: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ServiceCreate: {
            name: string;
            slug: string;
            description?: string;
            lifecycle: components["schemas"]["Lifecycle"];
            /** Format: uri */
            repoUrl?: string;
            /** Format: uri */
            runbookUrl?: string;
            /** Format: uuid */
            teamId: string;
            tags?: string[];
        };
        ServiceUpdate: {
            name: string;
            description?: string;
            lifecycle: components["schemas"]["Lifecycle"];
            /** Format: uri */
            repoUrl?: string;
            /** Format: uri */
            runbookUrl?: string;
            /** Format: uuid */
            teamId: string;
            tags?: string[];
        };
        ServiceList: {
            items: components["schemas"]["Service"][];
        };
        Error: {
            /** @description Machine-readable error code */
            code: string;
            /** @description Human-readable message */
            message: string;
        };
    };
    responses: {
        /** @description The request body or parameters are invalid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but lacking the required role on the owning team */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with an existing resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListServices: {
        parameters: {
            query?: {
                /** @description Filter by owning team slug */
                team?: string;
                /** @description Filter by lifecycle stage */
                lifecycle?: components["schemas"]["Lifecycle"];
                /** @description Filter by tag name */
                tag?: string;
                /** @description Free-text search over name and description */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    CreateService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Service created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    UpdateService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Updated service */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    DeleteService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    ListTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of teams */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ErrorResponse"];
        };
    };
}
